package com.sofar.fun.badge.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BADGE_RECORD".
 */
@Entity
public class BadgeRecord {

    @Id(autoincrement = true)
    private Long id;

    @Unique
    private Integer type;
    private Integer count;
    private Integer displayMode;

    @Generated
    public BadgeRecord() {
    }

    public BadgeRecord(Long id) {
        this.id = id;
    }

    @Generated
    public BadgeRecord(Long id, Integer type, Integer count, Integer displayMode) {
        this.id = id;
        this.type = type;
        this.count = count;
        this.displayMode = displayMode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Integer getDisplayMode() {
        return displayMode;
    }

    public void setDisplayMode(Integer displayMode) {
        this.displayMode = displayMode;
    }

}
