package com.sofar.fun.badge.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sofar.fun.badge.db.BadgeRecord;

import com.sofar.fun.badge.db.BadgeRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig badgeRecordDaoConfig;

    private final BadgeRecordDao badgeRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        badgeRecordDaoConfig = daoConfigMap.get(BadgeRecordDao.class).clone();
        badgeRecordDaoConfig.initIdentityScope(type);

        badgeRecordDao = new BadgeRecordDao(badgeRecordDaoConfig, this);

        registerDao(BadgeRecord.class, badgeRecordDao);
    }
    
    public void clear() {
        badgeRecordDaoConfig.clearIdentityScope();
    }

    public BadgeRecordDao getBadgeRecordDao() {
        return badgeRecordDao;
    }

}
